name: Release & Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type de version (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Run tests
      run: npm test
        
    - name: Bump version
      run: |
        echo "📈 Bumping version (${{ github.event.inputs.version_type }})"
        npm version ${{ github.event.inputs.version_type }}
        
    - name: Get new version
      id: version
      run: echo "new_version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
      
    - name: Push changes
      run: |
        git push origin main
        git push origin --tags
        
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.new_version }}
        release_name: Release v${{ steps.version.outputs.new_version }}
        body: |
          🚀 **@cosmospark/best-code v${{ steps.version.outputs.new_version }}**
          
          ## 📦 Installation
          ```bash
          npm install @cosmospark/best-code@${{ steps.version.outputs.new_version }}
          ```
          
          ## 🔧 Utilisation
          ```javascript
          const { hello, welcome, capitalize, slugify } = require('@cosmospark/best-code');
          
          console.log(hello('Monde')); // "Hello, Monde!"
          console.log(welcome('Dev')); // "Bienvenue Dev! Il est actuellement..."
          console.log(capitalize('test')); // "Test"
          console.log(slugify('Mon Titre')); // "mon-titre"
          ```
          
          ## 📋 Fonctionnalités
          - ✅ Salutations personnalisées
          - ✅ Messages de bienvenue avec timestamp
          - ✅ Capitalisation intelligente
          - ✅ Génération de slugs URL-friendly
          
          ## 🔗 Liens
          - [NPM Package](https://www.npmjs.com/package/@cosmospark/best-code)
          - [Documentation](https://github.com/GerardFevill/best-code#readme)
        draft: false
        prerelease: false
